name: 'Dart Analyzer'
description: 'Analyze a dart code'
author: 'Valentin Vignal'
inputs:
  fail-on-warnings:
    description: 'The action fails if any warning was found. This will always fail on errors. Optional. Default: `false`'
    default: 'false'
    required: false
  working-directory:
    description: 'The working directory. Optional. Default: `./`'
    default: ./
    required: false
  line-length:
    description: 'The maximum line length. Optional. The formatter will use its default: `80`'
    required: false
outputs:
  time: # id of output
    description:  'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
