name: 'Dart Analyze'
description: 'Analyze a dart code'
author: 'Valentin Vignal'
inputs:
  fail-on:
    description: 'When the action will fail. Optional. Option: `nothing`, `error`, `warning`, `info`. Default: `false`.'
    default: 'error'
    required: false
  working-directory:
    description: 'The working directory. Optional. Default: `./`'
    default: ./
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
